name: flockaway
favicon: null
layout_spectrum: 0.74639
typography_spectrum: 0.81406
title: flockaway
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#498022'
    - '#b57edc'
    - '#ffffff'
    - '#d0d7c5'
    - '#e4daf2'
  brandStrength: 0.07858899771235883
  lightness: 0.9598673556465656
  saturation: 0.19149902369827032
  rhythmicContrast: 0.9694616834167391
purpose: []
