name: flockaway
favicon: null
layout_spectrum: 0.9720750213600695
typography_spectrum: 0.40936364070512354
title: flockaway
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07858899771235883
  lightness: 0.9598673556465656
  saturation: 0.19149902369827032
  rhythmicContrast: 0.9694616834167391
purpose: []
